version: 1.0.{build}
branches:
  only:
  - master
skip_non_tags: true
image: Visual Studio 2017
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- cmd: nuget restore
build:
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
- provider: NuGet
  api_key:
    secure: diX6tHJxJvPAoo43liXAaTbTTgnSrklKn4Mb86gYS9Vqjpbyz1Z+QWZJWSrz8vJN